# Generated by Django 4.0.6 on 2022-07-30 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BodyStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('date_of_birth', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F'), ('Other', 'Other')], max_length=10)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('address_id', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('super_id', models.IntegerField()),
                ('slug', models.SlugField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('date_of_birth', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F'), ('Other', 'Other')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('dimensions', models.CharField(max_length=200)),
                ('capacity', models.CharField(max_length=200)),
                ('fuel_type', models.CharField(choices=[('Gas', 'Gas'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=20)),
                ('vehicle_condition', models.CharField(choices=[('Bad', 'Bad'), ('Fair', 'Fair'), ('Good', 'Good'), ('Brand New', 'Brand New')], max_length=20)),
                ('available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('rental_id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=200)),
                ('pickup_date', models.DateField()),
                ('return_date', models.DateField()),
                ('rental_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('rental_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=20)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalapp.customer')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalapp.vehicle')),
            ],
        ),
    ]
