# Generated by Django 4.0.6 on 2022-07-30 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employees',
            new_name='Employee',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='address_id',
            new_name='address',
        ),
    ]
