# Generated by Django 4.0.6 on 2022-09-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0007_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='address',
            field=models.CharField(blank=True, max_length=300, unique=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='myuser',
            name='postal_code',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
