# Generated by Django 4.0.6 on 2022-09-09 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0011_billingaddress_remove_myuser_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='billing',
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
