# Generated by Django 4.0.6 on 2022-09-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0013_myuser_address_myuser_city_myuser_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='BillingAddress',
        ),
    ]
