# Generated by Django 4.0.6 on 2022-09-11 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0014_alter_myuser_mobile_delete_billingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='province',
        ),
    ]
