# Generated by Django 4.0.6 on 2022-09-20 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0016_product_stripe_price_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stripe_price_id',
            new_name='price_id',
        ),
    ]
