# Generated by Django 4.0.6 on 2022-09-23 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0017_rename_stripe_price_id_product_price_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_id',
        ),
    ]
