# Generated by Django 4.0.6 on 2022-09-26 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0018_remove_product_price_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rent',
        ),
    ]
