# Generated by Django 4.0.6 on 2022-10-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0019_delete_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
