# Generated by Django 4.0.6 on 2022-09-12 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_address_order_city_order_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
