# Generated by Django 4.0.6 on 2022-09-20 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_email_order_firstname_order_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='braintree_id',
        ),
    ]
