# Generated by Django 4.0.6 on 2022-09-20 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_braintree_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='stripe_price_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
