# Generated by Django 4.0.6 on 2022-09-20 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderitem_stripe_price_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='stripe_price_id',
            new_name='price_id',
        ),
    ]
