# Generated by Django 4.0.6 on 2022-09-23 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_rename_stripe_price_id_orderitem_price_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price_id',
        ),
    ]
