# Generated by Django 4.0.6 on 2022-09-26 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_orderitem_price_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('slug', models.SlugField(max_length=200)),
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_date', models.DateTimeField()),
                ('customer_name', models.CharField(max_length=200)),
                ('rental', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
