# Generated by Django 4.0.6 on 2022-09-26 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='customer_name',
            new_name='customer',
        ),
    ]
