# Generated by Django 4.0.6 on 2022-09-26 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_rename_customer_name_invoice_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='status',
            new_name='paid',
        ),
    ]
