# Generated by Django 4.0.6 on 2022-09-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_rename_status_invoice_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='transaction_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
