# Generated by Django 4.0.6 on 2022-09-26 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_invoice_transaction_id'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='invoice',
            index_together={('transaction_id', 'slug')},
        ),
    ]
