# Generated by Django 4.0.6 on 2022-09-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_invoice_index_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
