# Generated by Django 4.0.6 on 2022-09-27 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_invoice_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='order_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
    ]
