# Generated by Django 4.0.6 on 2022-09-27 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_invoice_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='rental',
        ),
    ]
