# Generated by Django 4.0.6 on 2022-09-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_remove_invoice_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='transaction_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
